server:
  port: 8080
  servlet:
    context-path: /api/v1/ecsvolume/read

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: ECS-VOLUME-WRITE

app:
  file:
    path: /data/scheduler/task.log
