AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates backup task definition and schedule
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV)
    AllowedValues: [ 'DEV' ]
  Platform:
    Type: String
    Default: 'IDS'
    Description: Platform Name
  AppName:
    Type: String
    Default: 'BACKUP'
    Description: Application Name
  EfsStackName:
    Type: String
    Description: Name of the stack which is used to create EFS
  RoleStackName:
    Type: String
    Description: Name of the stack which is used to create Roles
  EcsClusterStackName:
    Type: String
    Description: Name of the stack which is used to create ECS cluster
  S3StackName:
    Type: String
    Description: Name of the stack which is used to create S3 buckets
  VpcStackName:
    Type: String
    Description: Name of the stack which is used to create VPC and Subnets
  SecurityGroupStackName:
    Type: String
    Description: Name of the stack used to create security group
Resources:
  # Cloud watch log group to which container send logs
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ECS/${Environment}/${Platform}/${AppName}'
      RetentionInDays: 1

  # The task definition. This is a simple metadata description of what container to run,
  # and what resource requirements it has.
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Environment}-${Platform}-${AppName}-TD-03'
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Join [ ':', [ !Ref 'RoleStackName', 'ECSTaskExecutionRoleArn' ] ]
      TaskRoleArn:
        Fn::ImportValue: !Join [ ':', [ !Ref 'RoleStackName', 'ECSTaskRoleArn' ] ]
      Volumes:
        - Name: EFS-SHARED
          EFSVolumeConfiguration:
            FilesystemId:
              Fn::ImportValue: !Join [ ':', [ !Ref 'EfsStackName', 'FileSystemId' ] ]
            #RootDirectory: /
            TransitEncryption: 'ENABLED'
            AuthorizationConfig:
              AccessPointId:
                Fn::ImportValue: !Join [ ':', [ !Ref 'EfsStackName', 'AccessPointId' ] ]
              IAM: ENABLED
        - Name: EFS-BACKUP
          EFSVolumeConfiguration:
            FilesystemId:
              Fn::ImportValue: !Join [ ':', [ !Ref 'EfsStackName', 'FileSystemId' ] ]
            #RootDirectory: /
            TransitEncryption: 'ENABLED'
            AuthorizationConfig:
              AccessPointId:
                Fn::ImportValue: !Join [ ':', [ !Ref 'EfsStackName', 'AccessPointResourceBackupId' ] ]
              IAM: ENABLED
      ContainerDefinitions:
        - Name: !Sub '${Environment}-${Platform}-${AppName}-CONTAINER'
          Cpu: 512
          Memory: 1024
          Image: asakchris/ecs-volume-backup:1.0.0-SNAPSHOT
          MountPoints:
            - SourceVolume: EFS-SHARED
              ContainerPath: /data/scheduler
            - SourceVolume: EFS-BACKUP
              ContainerPath: /data/backup
          Environment:
            - Name: BACKUP_S3_BUCKET
              Value:
                Fn::ImportValue: !Join [ ':', [ !Ref 'S3StackName', 'BackupBucket' ] ]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
  EventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AppName}-EVENTS_RULE-01'
      Description: !Sub 'Trigger ${AppName} according to the specified schedule'
      # Run every 15 minutes Monday through Friday
      ScheduleExpression: cron(0/15 * ? * MON-FRI *)
      RoleArn:
        Fn::ImportValue: !Join [ ':', [ !Ref 'RoleStackName', 'ECSTaskExecutionRoleArn' ] ]
      State: ENABLED
      Targets:
        - Id: !Sub '${AppName}-FARGATE-TASK-01'
          RoleArn:
            Fn::ImportValue: !Join [ ':', [ !Ref 'RoleStackName', 'ECSTaskBackupRoleArn' ] ]
          Arn:
            Fn::ImportValue: !Join [ ':', [ !Ref 'EcsClusterStackName', 'EcsClusterNameArn' ] ]
          EcsParameters:
            TaskDefinitionArn: !Ref ECSTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            PlatformVersion: 1.4.0
            NetworkConfiguration:
              AwsvpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                  - Fn::ImportValue: !Join [ ':', [ !Ref 'SecurityGroupStackName', 'ContainerSecurityGroupId' ] ]
                Subnets:
                  - Fn::ImportValue: !Join [ ':', [ !Ref 'VpcStackName', 'PrivateSubnetOne' ] ]
                  - Fn::ImportValue: !Join [ ':', [ !Ref 'VpcStackName', 'PrivateSubnetTwo' ] ]
